"""athlete_level_and_distance_category"""

revision = '2b1f6081abf8'
down_revision = '20260310_0013'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete_targets', sa.Column('distance_category', sa.String(length=30), nullable=True))
    op.add_column('athletes', sa.Column('athlete_level', sa.String(length=30), server_default='trained', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athletes', 'athlete_level')
    op.drop_column('athlete_targets', 'distance_category')
    # ### end Alembic commands ###

