"""add_bla_check_to_planned_sessions"""

revision = '974b1ced7ebb'
down_revision = '20260310_0011'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_sessions', sa.Column('bla_check', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planned_sessions', 'bla_check')
    # ### end Alembic commands ###

